permalink: pretty
markdown: kramdown

title: YubiSites
author: Prasad Tengse
description:
    List of sites with Two Factor Auth support which includes SMS, email,
    phone calls, hardware, and software.
baseurl: ""
url: https://yubikey.prasadt.com
repo: https://github.com/tprasadtp/yubi-otp-sites
img: img/logo.png
include: ['_pages','mdl']
exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor
    - Dockerfile
    - docker-compose.yml

google-anaytics: UA-101760811-4