websites:
    - name: Dashlane
      url: https://dashlane.com
      img: dashlane.png
      supported: Yes
      u2f: Yes
      yubiotp: No
      hotp: Yes
      doc: https://support.dashlane.com/hc/en-us/articles/206177031-Protect-your-account-using-Two-Factor-Authentication-via-an-OTP-Security-Key

    - name: Lastpass
      url: https://lastpass.com
      img: lastpass.png
      supported: Yes
      u2f: No
      yubiotp: Yes
      hotp: No
      exceptions:
        text: Lastpass Premium subscription is required to use Yubicloud OTP.
      doc: https://lastpass.com/yubico

    - name: Norton Account
      url: https://login.norton.com
      img: vip.png
      supported: Yes
      u2f: Yes
      yubiotp: No
      hotp: Yes
      exceptions:
        text: No offical Methods Available for HMAC-HOTP unless Yubikey VIP is used. Click for more info.
        link: Yes
      doc: https://support.norton.com/sp/en/us/home/current/solutions/v100023155_NortonM_Retail_1_en_us